### ISSUE TITLE
Double jump does not work

### ISSUE THREAD

**Issue by CoderXL1** [Alpha-s-Stuff/TinkersConstruct#102]
### Minecraft Version

1.20.1

### Fabric Version

0.15.3

### Fabric API Version

0.91.0

### Hephaestus Version

3.6.3.240

### Describe your issue

The double jump upgrade does not work. Other upgrades like the frost walker are working properly. I am NOT sure if my method of applying double jump is correct. I tried double-clicking the space bar in survival mode but nothing happened. I also tried pressing 'I'(The default key for Leggings Interaction) but still no response.

### Other mods

PortingLib 2.1.1163+1.20.1

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by KonSola5** [comment]
It's because the info about the extra jumps is stored in a capability, which at this point is null for  some reason:
https://github.com/Alpha-s-Stuff/TinkersConstruct/blob/8d64ca2073c528d4183dd6add172756c99bcb018/src/main/java/slimeknights/tconstruct/tools/modifiers/ability/armor/DoubleJumpModifier.java#L51-L74

(the `PersistentDataCapability.CAPABILITY` is null)

**Comment by KonSola5** [comment]
![debug](https://github.com/Alpha-s-Stuff/TinkersConstruct/assets/125081901/227c660a-bdb2-4715-adc8-cca516cc400c)

**Comment by AlphaMode** [comment]
Fixed in https://github.com/Alpha-s-Stuff/TinkersConstruct/commit/406cfa581a47288c01b1a1d28aa614f9f54941ed
