### ISSUE TITLE
Melting ability does not transfer to fuel tanks

### ISSUE THREAD

**Issue by SirOofington** [Alpha-s-Stuff/TinkersConstruct#29]
### Minecraft Version

1.18.2

### Fabric/Quilt Version

Fabric 0.14.9

### Fabric/Quilt API Version

Fabric API 0.58.0 - 1.18.2

### Tinkers' Construct Version

1.18.2-3.5.2.149

### Describe your issue

After filling my iron sword with the melting ability with blazing blood, I am unable to empty the fluid into a seared fuel tank by interacting with it. Tried with different tools, materials, mods, no mods, different worlds, but it doesn't seem possible to empty the tool other than also having the bucket ability, pouring it out, and then using a normal bucket to put it in the tank.

### Other mods

None

### Tried reproducing with just Tinkers?

Yes

### Performance Enchancers

None of the above

### Searched for known issues?

Checked pinned issues, Searched open issues, Searched closed issues, Checked the FAQ

**Comment by Misstborn** [comment]
Having the exact same issue, can't empty it no matter what. The only workaround would be to add bucketing too and then transfer from sword to world to bucket to tank.

**Comment by AlphaMode** [comment]
The problem is that tools aren't registering their inventory to the transfer api this is going to be a bit of work to implement this. Since the two systems that forge and fabric use are very different. I wouldn't except this to be fixed anytime soon as I don't have the motivation right now to fix this issue as it would be time consuming for me.

**Comment by ruifengx** [comment]
Any updates on this? 

> I don't have the motivation right now to fix this issue as it would be time consuming for me.

When you said this, did you mean that it would be a lot of work, or that it would involve some major redesign? If it is the former case, I would like to take some efforts to try and fix it myself.

**Comment by AlphaMode** [comment]
> Any updates on this?
> 
> > I don't have the motivation right now to fix this issue as it would be time consuming for me.
> 
> When you said this, did you mean that it would be a lot of work, or that it would involve some major redesign? If it is the former case, I would like to take some efforts to try and fix it myself.

I've disabled the recipe in dev already.
Currently the project doesn't compile if your just cloning directly from github. This is because I was attempting to update to latest upstream, and i never finished. I probably shouldn't have pushed to the main branch. So if your looking to actually fix this you should use the commit that last compiled. In regards to when. I plan when Tinkers updates to 1.19. This is primarily due to 1.18 being pre porting lib modules since this mod heavily depends on porting lib, and the fact forge redid there model loading system in 1.19. Your more then welcome to submit a PR to fix the issue yourself.
